// products.js
const products = [
    {
        name: 'Upper Light',
        price: '$119.99',
        image: '/light1 (1).webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque leo nec magna varius, nec bibendum purus tincidunt. Integer non libero nec nulla facilisis tincidunt.'
    },
    {
        name: 'Wall Light',
        price: '$109.99',
        image: '/light2.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque leo nec magna varius, nec bibendum purus tincidunt. Integer non libero nec nulla facilisis tincidunt.'
    },
    {
        name: 'Floor Lamp',
        price: '$199.99',
        image: '/light3.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque leo nec magna varius, nec bibendum purus tincidunt. Integer non libero nec nulla facilisis tincidunt.'
    },
    {
        name: 'Table Lamp',
        price: '$149.99',
        image: '/light4.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque leo nec magna varius, nec bibendum purus tincidunt. Integer non libero nec nulla facilisis tincidunt.'
    },
    {
        name: 'Upper Light',
        price: '$139.99',
        image: '/light5.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque leo nec magna varius, nec bibendum purus tincidunt. Integer non libero nec nulla facilisis tincidunt.'
    },
    {
        name: 'Pendant Light',
        price: '$189.99',
        image: '/light6.webp',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam scelerisque leo nec magna varius, nec bibendum purus tincidunt. Integer non libero nec nulla facilisis tincidunt.'
    }
];

export default products;